eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.43.184:8070/eureka/
    instance:
      hostname: eurekaserver

spring:
  application:
    name: userservice